# Generated by Django 3.2.13 on 2023-09-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('origem', models.CharField(choices=[('EUA', 'Estados Unidos'), ('ALE', 'Alemanha'), ('RUS', 'Rússia')], max_length=3)),
                ('calibre', models.IntegerField(choices=[('NATO', '556'), ('SOV', '762'), ('AUS', '9')])),
            ],
        ),
        migrations.CreateModel(
            name='Mapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=50)),
                ('modos', models.CharField(max_length=50)),
            ],
        ),
    ]
