# Generated by Django 3.2.13 on 2023-09-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdojoao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaMapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='armas',
            name='calibre',
            field=models.CharField(choices=[('NATO', '556'), ('SOV', '762'), ('AUS', '9')], max_length=50),
        ),
    ]
